version: "3"
services:
  broker:
    build: ./broker/
    volumes: 
      - broker:/var/lib
    networks: 
      - default
    restart: on-failure

  database:
    depends_on: 
      - broker
    build: ./influxdb/
    volumes: 
      # Mount for influxdb data directory
      - ${INFLUXDB_DATA_VOLUME}:/var/lib/influxdb
      # Mount for influxdb configuration
      - ${INFLUXDB_CONFIG_VOLUME}:/etc/influxdb/
    ports:
    - "8086:8086"
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    restart: on-failure

  node-red:
    depends_on:
      - database
      - broker
    build: ./nodered
    volumes:
      - nodered:/data 
    ports:
      - "1880:1880"
      - "1999:1999"
      - "2000:2000"
    networks: 
      - default
    restart: on-failure

networks:
  default:

volumes:
  nodered:
  influxdb:
  broker:
    


