version: "3"
services:
  broker:
    image: eclipse-mosquitto
    #volumes:
    #  - "./mosquitto:/mosquitto"
    networks: 
      - default
    restart: on-failure

  database:
    depends_on: 
      - broker
    image: influxdb:latest
    volumes: 
      - influxdb:/var/lib/influxdb 
    restart: on-failure

  node-red:
    depends_on:
      - database
      - broker
    build: ./nodered
    volumes:
      - nodered:/data 
    #user: "0"
    ports:
      - "1880:1880"
      - "1999:1999"
      - "2000:2000"
    networks: 
      - default
    restart: on-failure

networks:
  default:

volumes:
  nodered:
  influxdb:
    


